const PDFDocument = require('pdfkit');

const generateBrandPDF = (brandKit, businessName) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc
      .fontSize(28)
      .fillColor('#c9a84c')
      .text('PAHCHAAN AI', { align: 'center' })
      .fontSize(14)
      .fillColor('#666')
      .text('Brand Identity Kit', { align: 'center' })
      .moveDown(2);

    // Business Name
    doc
      .fontSize(22)
      .fillColor('#1a1410')
      .text(brandKit.brandName || businessName)
      .moveDown(0.5);

    // Tagline
    doc
      .fontSize(14)
      .fillColor('#c9a84c')
      .text(`"${brandKit.tagline}"`)
      .moveDown(1.5);

    // Brand Story
    doc.fontSize(12).fillColor('#333').text('Brand Story', { underline: true }).moveDown(0.3);
    doc.fontSize(11).fillColor('#555').text(brandKit.brandStory || '').moveDown(1.5);

    // Colors
    doc.fontSize(12).fillColor('#333').text('Brand Colors', { underline: true }).moveDown(0.3);
    (brandKit.colors || []).forEach((color) => {
      doc.fontSize(11).fillColor(color).text(`● ${color}`);
    });
    doc.moveDown(1.5);

    // Fonts
    doc.fontSize(12).fillColor('#333').text('Brand Fonts', { underline: true }).moveDown(0.3);
    (brandKit.fonts || []).forEach((font) => {
      doc.fontSize(11).fillColor('#555').text(`• ${font}`);
    });
    doc.moveDown(1.5);

    // Brand Voice
    doc.fontSize(12).fillColor('#333').text('Brand Voice', { underline: true }).moveDown(0.3);
    doc.fontSize(11).fillColor('#555').text(brandKit.brandVoice || '').moveDown(1.5);

    // Social Bio
    doc.fontSize(12).fillColor('#333').text('Social Media Bio', { underline: true }).moveDown(0.3);
    doc.fontSize(11).fillColor('#555').text(brandKit.socialBio || '').moveDown(1.5);

    // Footer
    doc
      .fontSize(10)
      .fillColor('#999')
      .text('Generated by Pahchaan AI — pahchaan.ai', { align: 'center' });

    doc.end();
  });
};

module.exports = { generateBrandPDF };